org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true
android.enableJetifier=true

# Ensure Gradle toolchains can find JDK 17 (required by AGP/React Native)
org.gradle.java.home=E:/Eclipse Adoptium/jdk-17.0.19.10-hotspot
org.gradle.java.installations.paths=E:/Eclipse Adoptium/jdk-17.0.19.10-hotspot
# Gradle user home on E drive to save C drive space
org.gradle.user.home=E:/Android/.gradle
